#!/bin/bash

FLAGS="$*"

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
BLUE="${BOLD}$(tput setaf 4)"
GREEN="${BOLD}$(tput setaf 2)"
WHITE="${BOLD}$(tput setaf 7)"

msg() {
	local mesg=$1; shift
	printf "${GREEN}==> ${ALL_OFF}${BOLD}${mesg}${ALL_OFF}\n" "$*" >&2
}

msg2() {
	local mesg=$1; shift
	printf "${BLUE}  -> ${ALL_OFF}${BOLD}${mesg}${ALL_OFF}\n" "$@" >&2
}

confirm() {
	local -l reply # convert to lowercase on assignment
	local msg=${1:-Continue?}

	# make sure stdin is a terminal
	if [[ ! -t 0 ]]; then
		exec </dev/tty
	fi

	# actually print the prompt, return according to response
	read -p "${BLUE}:: ${ALL_OFF}${BOLD}$msg${ALL_OFF} [Y/n] " reply >/dev/tty
	[[ -z $reply || $reply = y?(es) ]]
}

# extract the protocol from a source entry - return "local" for local sources
get_protocol() {
	if [[ $1 = *://* ]]; then
		# strip leading filename
		local proto="${1##*::}"
		printf "%s\n" "${proto%%://*}"
	else
		printf "%s\n" local
	fi
}

# extract the filename from a source entry
get_filename() {
	local netfile=$1

	# if a filename is specified, use it
	if [[ $netfile = *::* ]]; then
		printf "%s\n" ${netfile%%::*}
		return
	fi

	local proto=$(get_protocol "$netfile")

	case $proto in
		bzr*|git*|hg*|svn*)
			filename=${netfile%%#*}
			filename=${filename%/}
			filename=${filename##*/}
			if [[ $proto = git* ]]; then
				filename=${filename%%.git*}
			fi
			;;
		*)
			# if it is just an URL, we only keep the last component
			filename="${netfile##*/}"
			;;
	esac
	printf "%s\n" "${filename}"
}

update_git_mirror() {
	git fetch >/dev/null
	git rev-list HEAD...origin/$1 --count
}

show_git_log() {
	git log --oneline --decorate --graph origin/$1
}

# XXX: incorrent hg instructions
update_hg_mirror() {
	hg pull >/dev/null
	commits=$(hg summary --remote | grep "update:" | wc -l | sed -e 's/^ *//')
	echo $((commits - 1))
}

show_hg_log() {
	hg log | less
}

update() {
	local package="$1"
	local netfile="$2"
	local proto=$(get_protocol "$netfile")

	case $proto in
	git*)
		local repo=$(get_filename "$netfile")
		local fragment=${netfile#*#}
		local branch="master"

		if [[ "$fragment" != "$netfile" && ${fragment%%=*} == "branch" ]]; then
			branch=${fragment##*=}
		fi

		(cd "$package/$repo" && git fetch --all >/dev/null)
		local commits=$(cd "$package/src/$repo" && update_git_mirror $branch)

		if (( commits > 0 )); then
			msg2 "$package is $commits commits behind origin/$branch"
			confirm "View git log?"    && (cd "$package/src/$repo" && show_git_log $branch)
			confirm "Rebuild package?" && (cd "$package" && makepkg $FLAGS)
		fi
		;;
	hg*)
		local repo=$(get_filename "$netfile")
		# local fragment=${netfile#*#}
		# local branch="master"

		# if [[ "$fragment" != "$netfile" && ${fragment%%=*} == "branch" ]]; then
		# 	branch=${fragment##*=}
		# fi

		(cd "$package/$repo" && hg pull >/dev/null)
		local commits=$(cd "$package/src/$repo" && update_hg_mirror $branch)

		if (( commits > 0 )); then
			msg2 "$package is $commits commits behind origin/$branch"
			confirm "View git log?"    && (cd "$package/src/$repo" && show_hg_log $branch)
			confirm "Rebuild package?" && (cd "$package" && makepkg $FLAGS)
		fi
		;;
	esac
}

check_updates() {
	local package="$1"
	local sources=($(source "$package/PKGBUILD"; echo $source))

	for source in ${sources[@]}; do
		update "$package" "$source"
	done
}

# PROGRAM START

if [[ -f "PKGBUILD" ]]; then
	msg "Checking ${PWD##*/}..."
	check_updates .
else
	for dir in *; do
		[[ ! -d "$dir" ]] && continue
		[[ ! -f "$dir/PKGBUILD" ]] && continue
		msg "Checking ${dir}..."
		check_updates "$dir"
	done
fi

msg "Updating vodik.db..."
[[ -f "$HOME/.makepkg.conf" ]] && source "$HOME/.makepkg.conf"
[[ -d "$PKGDEST" ]] && repoman -Ucs "$PKGDEST/vodik.db"
